    CREATE TABLE IF NOT EXISTS ODONTOLOGOS (
        ID INT AUTO_INCREMENT PRIMARY KEY,
         NOMBRE VARCHAR(30),
       APELLIDO VARCHAR(30),
        MATRICULA VARCHAR(15) UNIQUE);
         "CREATE TABLE IF NOT EXISTS PACIENTES (
                ID INT AUTO_INCREMENT PRIMARY KEY,
                 NOMBRE VARCHAR(30),
               APELLIDO VARCHAR(30),
                DNI VARCHAR(15) UNIQUE,ALTAFECHA DATE)";






